### ISSUE TITLE
What does this project do?

### ISSUE THREAD

**Issue by Boren** [adriantuftisdahl/MyFirstReact#1]
Hi,

I'm just wondering what this project does?
What do I use it for?

Best regards

**Comment by adriantuftisdahl** [comment]
I have made a template for React-projects, so that others can clone the repo and start up a React-project themselves. It has been sweat, blood and tears, but I hope that all the files that I have made here are reusable and that people will start writing React. 
Best Regards

**Comment by adriantuftisdahl** [comment]
Ffs, is this issue resolved already??
